<?php

namespace App\Models\Cliente;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    use HasFactory;

    protected $fillable = [
        'id_representante',
        'id_indicacao',
        'tipo',
        'token',
        'data_inst',
        'codico',
        'codigo',
        'nome',
        'nomefantasia',
        'cpf_cnpj',
        'ie',
        'inscricao_municipal',
        'residente_domiciliada',
        'responsavel',
        'cpf_resp',
        'email_resp',
        'senha_resp',
        'aut_envio_email_resp',
        'rg',
        'fone_resp1',
        'fone_resp2',
        'orgao_expedidor',
        'data_nasc_resp',
        'responsavel2',
        'cpf_resp2',
        'email_resp2',
        'aut_envio_email_resp2',
        'nao_faz_parte_contrato2',
        'rg2',
        'orgao_expedidor2',
        'data_nasc_resp2',
        'email',
        'senha',
        'status_senha',
        'site',
        'end',
        'numero',
        'cep',
        'complemento',
        'bairro',
        'cidade',
        'uf',
        'ddd',
        'skype',
        'telefone',
        'telefone2',
        'banco',
        'operacaocaixa',
        'tipo_conta',
        'agencia',
        'agenciadv',
        'conta',
        'contadv',
        'cod_pago',
        'senha_pago',
        'obs',
        'obs_tendimento',
        'servicos_c',
        'nivel',
        'data',
        'data_cadastro',
        'id_usuario_cadastro',
        'id_usuario_auto_repre',
        'versao',
        'data_atu_ver',
        'usuario_atu',
        'usuario_atu_validador',
        'horario_atu_validador',
        'validador',
        'status',
        'contato_ativo_cliente',
        'em_implantacao',
        'dta_em_implantacao',
        'dta_concluido_implantacao',
        'contrato',
        'logo',
        'id_remoto',
        'senha_remoto',
        'data_remoto',
        'data_torna_cliente',
        'certificado',
        'data_certificado',
        'usuario_certificado',
        'senha_certificado',
        'cadastro_site',
        'vinculado',
        'termos_concordo',
        'termos_texto',
        'termos_dta_concordo',
        'solicita_dados',
        'cliente_parceiro',
    ];
}
