<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Spatie\Permission\Models\Role as ModelsRole;

class Role extends ModelsRole
{
    use HasFactory;

    protected $fillable = [
        'name',
        'guard_name',
        'mostrar_valor_tela_atendimento',
        'pedidos_realizados',
        'dashboard_suporte',
        'dashboard_bhair',
        'menu_cliente',
        'menu_cliente_cadastrar_cliente',
        'menu_cliente_dados',
        'menu_cliente_dados_status_cliente',
        'menu_cliente_dados_alterar_termos',
        'menu_cliente_dados_enviar_boas_vindas',
        'menu_cliente_dados_senha_cliente',
        'menu_cliente_dados_ver_dados_bancarios',
        'faturas',
        'faturas_alterar_status_da_fatura',
        'faturas_reprocessar_serial',
        'faturas_cadastrar_faturas',
        'faturas_alterar_fatura',
        'faturas_excluir_fatura',
        'serial',
        'serial_gerar_serial_temporario_com_limite_excedido',
        'servicos_adicionar_servicos',
        'servicos_excluir_servicos',
        'servicos_alterar_servicos',
        'servicos_alterar_servicos_versao',
        'servicos_alterar_servicos_implantacao',
        'servicos_servicos_log',
        'servicos_visualizar_servicos',
        'servicos_gerar_serial_servicos',
        'n_profissionais',
        'saikoo_web',
        'manual_de_implantacao',
        'relato_de_implantacao',
        'contatos_com_o_cliente',
        'propostas',
        'menu_ata_de_reuniao',
        'cadastrar_ata_de_reuniao',
        'menu_chamado',
        'menu_agenda',
        'menu_ci',
        'menu_relatorios',
        'menu_relatorios_pagto_aprovados',
        'menu_relatorios_pagto_em_aberto',
        'menu_relatorios_versao_do_sistema',
        'menu_relatorios_log_faturas_e_servicos',
        'menu_relatorios_servicos_contratados',
        'menu_relatorios_tickets_dev_prazo',
        'menu_relatorios_list_cliente_chamados_nos_ultimos_20_dias',
        'ver_remuneracoes',
        'lancamento_de_remuneracao',
        'ticket_desenvolvimento',
        'menu_prioridade_de_tickets',
        'alterar_prioridade_de_ticket',
        'atualizacoes',
        'clientes_versoes',
        'arquivos',
        'marketing',
        'configuracoes',
        'configuracoes_representantes',
        'configuracoes_versao_do_sistema',
        'menu_acesso',
        'menu_acesso_usuarios',
        'menu_acesso_perfil',
    ];
}
